GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name" : "permana",
    "email" : "permana@gmail.com",
    "gender" : "laki-laki"
}

###
PATCH   http://localhost:5000/users/1
Content-Type: application/json

{
    "name" : "M fikri",
    "email" : "mfikri@gmail.com",
    "gender" : "laki-laki"
}

###
DELETE http://localhost:5000/users/2